### ISSUE TITLE
Explorer is showing blank lines

### ISSUE THREAD

**Issue by worming004** [evilz/vscode-reveal#284]
![image](https://user-images.githubusercontent.com/23192591/64856367-1ae5a300-d622-11e9-9809-49ea8d4c9421.png)

With this basic example, the explorer consider blank lines as headers

This happen with version 3.4.0 & 3.3.2
I didn't tried previous versions.

specs: 
![image](https://user-images.githubusercontent.com/23192591/64856775-0f46ac00-d623-11e9-9ff1-01c257e5a4e8.png)

**Comment by evilz** [comment]
Can you try the new version 4.0.1 and let me know please.

**Comment by wiheto** [comment]
I got this issues as well. Old presentations stopped working. Downgraded to 3.4.0 and everything worked again. 

Specs: 

Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:30:08.229Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.0.0-29-generic snap

**Comment by evilz** [comment]
Can you check the separator configuration ^^^

Or send me you file.

Thank

**Comment by worming004** [comment]
I added you in my private repository https://github.com/worming004/neo4j-talk
I tried with version 4.0.1 & 4.0.2, I still get the same issue

**Comment by evilz** [comment]
LGTM

**Comment by AceTheWiz** [comment]
I have the same issue: two blank slides inserted after each separator "---".
![image](https://user-images.githubusercontent.com/11596641/70614198-c77bf480-1c12-11ea-8211-dfefbbd6ba60.png)

I have determined that this is not caused by blank lines in the markdown.
I thought it might be caused by the interpretation of line endings on Windows (CRLF vs LF) but this makes no difference.
My separator setting is the default. I have tried using different separators. e.g. "====" and "***" but this made no difference.

My setup:
![image](https://user-images.githubusercontent.com/11596641/70614169-b7fcab80-1c12-11ea-9543-504924e25eec.png)

vscode-reveal: v4.0.3

Can you share the solution for this issue please.

**Comment by evilz** [comment]
thank for reporting this !

**Comment by drk-mtr** [comment]
Wonder whether this should be in the instructions :) Great plugin but a little tough to get working.
