### ISSUE TITLE
Can we scale the font size through out the document?

### ISSUE THREAD

**Issue by colorizer** [evilz/vscode-reveal#709]
Is there a way to reduce the font size through out the document? All the themes seem to have font size which is too big for my screen. 
(Sorry if this seems too trivial, I don't have much knowledge regarding html/css).

**Comment by colorizer** [comment]
I've created a custom theme as per [this](https://github.com/hakimel/reveal.js/blob/master/css/theme/template/exposer.scss) where I've changed the font sizes to small ones (like 12 px) and loaded in the front matter with `customTheme: "mytheme.css"` but the changes are not reflected.

**Comment by fuhrmanator** [comment]
Presentations can easily have text that is too small to read, especially since not everyone has a big monitor. RevealJS has made a lot of assumptions about that. Since the pandemic, I have unfortunately seen lots of presentations with text that was too small, especially over Zoom where zoom where the presentation is in a window that may not be on a full screen, or may have other information inside it (the list of attendees, etc.).

That said, themes (e.g., beige) are picked up at `http://localhost:xxxxx/libs/reveal.js/3.8.0/css/theme/beige.css`, at least on my Windows system. Did you put your custome theme there? Beware that the installation of the extension will likely overwrite that space. I'm not aware of how you can point to a theme in a different directory with this extension.

You can verify if your theme is being loaded by using the Inspect feature of Chrome or another browser that shows where CSS are being loaded.

**Comment by evilz** [comment]
customTheme can do that
